{{- if .Values.global.gardenlet.enabled }}
---
apiVersion: {{ include "rbacversion" . }}
kind: Role
metadata:
  name: gardener.cloud:system:gardenlet
  namespace: default
  labels:
    app: gardener
    role: gardenlet
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - get
  - list
  - watch
{{- end }}
